platform :ios, '10.0'
use_frameworks!

target 'KMNumber_Example' do
  pod 'KMNumber', :path => '../'

  target 'KMNumber_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
